name: CI - Tests & Linting

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (Flake8)
        run: |
          flake8 dags tests --max-line-length=100

      - name: Format check (Black)
        run: |
          black --check dags tests

      - name: Run unit tests
        run: |
          pytest tests/
